In [2]:
import pandas as pd
import numpy as np
import os

In [3]:
ls

cat_estacion.csv     Datos_dia.ipynb    HISTORICO/           Modelos/
Concatenacion.ipynb  Datos_Procedados/  Limpieza_dia.ipynb
Datos/               Fotos/             Limpieza_hora.ipynb

In [ ]:
cd RAMA

In [ ]:
ls

In [4]:
df = pd.read_excel('/home/alberto/Documentos/Proyecto_Mineria/Datos/REDMET/2008WSP.xls')

In [5]:
df.describe()

,HORA,TAC,FAC,SAG,TLA,XAL,MER,PED,CES,PLA,VIF,CUA,TPN,MON,TAH,SUR
count,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000,8784.000000
mean,12.500000,-10.936077,-43.928245,-2.407741,-1.184756,-2.211976,-2.381557,-1.461646,-19.699442,-12.398338,-6.381865,-8.185838,-24.494422,-14.063286,-25.805123,-63.695947
std,6.922581,33.176244,50.054347,21.138159,17.516345,19.120978,18.958105,16.886181,40.689292,34.391312,27.447526,30.782495,44.426718,36.953533,45.065045,48.063033
min,1.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000,-99.000000
25%,6.750000,0.700000,-99.000000,1.100000,1.100000,0.700000,0.600000,0.800000,0.300000,0.500000,0.800000,1.100000,-99.000000,0.500000,-99.000000,-99.000000
50%,12.500000,1.200000,0.500000,1.800000,1.700000,1.200000,1.100000,1.300000,0.800000,0.900000,1.300000,1.900000,1.400000,1.100000,1.000000,-99.000000
75%,18.250000,1.900000,1.400000,3.000000,2.500000,2.000000,1.800000,1.800000,1.300000,1.500000,2.100000,2.800000,2.100000,2.400000,2.100000,0.900000
max,24.000000,5.600000,6.700000,7.400000,6.800000,6.500000,4.900000,6.300000,6.200000,5.700000,7.000000,8.500000,9.200000,9.500000,8.100000,5.600000

In [6]:
df.replace(99,-99, inplace=True)

In [7]:
df = df.replace(-99, np.nan)

In [8]:
df.head()

,FECHA,HORA,TAC,FAC,SAG,TLA,XAL,MER,PED,CES,PLA,VIF,CUA,TPN,MON,TAH,SUR
0,2008-01-01,1,1.3,1.1,2.3,1.6,1.1,1.4,1.7,0.5,NaN,1.0,0.8,2.0,1.2,2.3,NaN
1,2008-01-01,2,0.9,1.1,2.0,1.7,0.5,1.1,2.0,0.2,NaN,0.7,1.0,1.9,0.2,0.9,NaN
2,2008-01-01,3,1.0,0.2,2.1,1.9,0.1,0.7,1.4,0.4,NaN,0.9,1.3,2.7,0.7,1.5,NaN
3,2008-01-01,4,1.1,1.5,1.6,2.3,0.7,0.6,1.6,0.3,0.8,0.8,0.2,2.2,0.7,1.2,NaN
4,2008-01-01,5,0.6,0.6,1.0,NaN,0.3,1.4,1.6,0.3,0.7,NaN,0.5,2.1,0.5,0.7,NaN

In [9]:
df.pivot_table(columns='HORA')

HORA,1,2,3,4,5,6,7,8,9,10,...,15,16,17,18,19,20,21,22,23,24
CES,0.834615,0.826148,0.812057,0.808633,0.751079,0.724382,0.708392,0.793750,0.842014,0.833219,...,1.523129,1.757732,2.056757,2.215753,1.982034,1.692177,1.360751,1.147811,0.995238,0.931615
CUA,1.976364,1.945566,1.919385,1.830769,1.765758,1.729091,1.698480,1.552615,1.446154,1.797576,...,2.643119,2.709846,2.925460,2.984498,3.029909,2.929042,2.729091,2.494578,2.198193,2.079403
FAC,1.257711,1.113930,1.013846,1.023500,1.052308,0.980829,1.016410,0.879695,0.808416,1.134158,...,1.865842,2.127861,2.327228,2.457635,2.442439,2.155721,1.994030,1.867488,1.723267,1.457921
MER,1.317429,1.184241,1.054386,0.940118,0.902959,0.839535,0.769006,0.814000,0.836080,0.855085,...,1.490756,1.746667,2.014804,2.260556,2.190833,1.973538,1.769444,1.644538,1.559104,1.494302
MON,1.387097,1.347896,1.303279,1.200654,1.066776,0.998013,0.929470,0.969868,1.232026,1.485113,...,2.924262,3.385942,3.676206,3.673871,3.478758,2.956818,2.452581,1.989103,1.694888,1.504473
PED,1.392717,1.322571,1.225284,1.180682,1.116480,1.084358,1.054775,0.864407,0.862994,1.058640,...,1.682768,1.892265,2.029917,2.218889,2.157895,1.936364,1.727978,1.616156,1.548189,1.486275
PLA,1.091429,0.961270,0.880386,0.854545,0.797377,0.755700,0.728065,0.670570,0.817081,0.982445,...,1.481308,1.645511,1.835423,1.997531,1.910494,1.730462,1.641975,1.541486,1.412579,1.246057
SAG,2.009375,1.856571,1.735511,1.631805,1.560458,1.569452,1.491379,1.571098,1.612464,1.526901,...,2.430172,2.766949,3.279272,3.643343,3.485955,3.256695,2.943750,2.681609,2.452125,2.229395
SUR,1.646512,1.459375,1.291538,1.225000,1.194574,1.138760,1.110769,1.098450,1.108661,1.149206,...,1.762400,2.068800,2.368217,2.749612,2.826718,2.603053,2.470992,2.345385,2.170229,1.869231
TAC,1.545794,1.353438,1.198438,1.134177,1.049524,1.013694,1.018910,0.991250,0.990938,1.093458,...,1.768770,1.927554,2.188272,2.430183,2.408642,2.133951,2.060062,1.960308,1.840994,1.669969
TAH,1.525564,1.288346,1.230451,1.079775,1.032453,0.949624,1.013962,0.970037,1.234091,1.488390,...,2.699621,3.032319,3.290114,3.472388,3.342803,2.633962,2.241288,1.917978,1.834328,1.716917
TLA,1.833333,1.719658,1.595775,1.522129,1.452991,1.450712,1.459483,1.438873,1.320113,1.340336,...,2.105367,2.393872,2.709418,3.008056,2.994972,2.683240,2.467324,2.320506,2.132295,1.961517
TPN,2.072932,1.979926,1.861338,1.840221,1.807463,1.763941,1.706618,1.149451,0.989455,1.369004,...,2.104815,2.312774,2.532601,2.818613,2.939338,2.856250,2.341176,2.078148,2.036431,2.064925
VIF,1.320833,1.210511,1.087311,1.068862,0.994277,0.940120,0.951515,1.049848,1.145646,1.135714,...,2.188095,2.657396,3.104094,3.300000,3.186257,2.740233,2.321345,1.957558,1.678006,1.451917
XAL,1.080223,0.946067,0.906250,0.821739,0.847230,0.919130,0.877714,0.957429,1.129178,1.222767,...,1.950992,2.246439,2.606215,2.822067,2.748451,2.503361,2.132961,1.826331,1.493889,1.247632

In [10]:
Prom=df.mean(axis=1)
Max=df.max(axis=1)
Min=df.min(axis=1)
df.eval("Min= @Min.values", inplace=True)
df.eval("Max= @Max.values", inplace=True)
df.eval("Prom = @Prom.values", inplace=True)

In [12]:
df.head(-1)

,FECHA,HORA,TAC,FAC,SAG,TLA,XAL,MER,PED,CES,PLA,VIF,CUA,TPN,MON,TAH,SUR,Min,Max,Prom
0,2008-01-01,1,1.3,1.1,2.3,1.6,1.1,1.4,1.7,0.5,NaN,1.0,0.8,2.0,1.2,2.3,NaN,0.5,2.3,1.378571
1,2008-01-01,2,0.9,1.1,2.0,1.7,0.5,1.1,2.0,0.2,NaN,0.7,1.0,1.9,0.2,0.9,NaN,0.2,2.0,1.157143
2,2008-01-01,3,1.0,0.2,2.1,1.9,0.1,0.7,1.4,0.4,NaN,0.9,1.3,2.7,0.7,1.5,NaN,0.1,3.0,1.278571
3,2008-01-01,4,1.1,1.5,1.6,2.3,0.7,0.6,1.6,0.3,0.8,0.8,0.2,2.2,0.7,1.2,NaN,0.2,4.0,1.306667
4,2008-01-01,5,0.6,0.6,1.0,NaN,0.3,1.4,1.6,0.3,0.7,NaN,0.5,2.1,0.5,0.7,NaN,0.3,5.0,1.176923
5,2008-01-01,6,0.6,0.4,1.1,NaN,0.1,0.6,1.5,NaN,1.0,NaN,1.2,2.0,0.6,0.5,NaN,0.1,6.0,1.300000
6,2008-01-01,7,1.1,0.8,1.3,NaN,0.1,0.4,1.7,NaN,0.8,NaN,0.3,2.4,0.7,0.4,NaN,0.1,7.0,1.416667
7,2008-01-01,8,1.3,0.4,2.4,2.5,1.2,0.8,1.5,NaN,0.5,0.5,1.6,2.3,0.5,0.6,NaN,0.4,8.0,1.721429
8,2008-01-01,9,3.3,3.0,4.4,3.3,3.3,0.7,2.7,0.8,3.0,1.3,3.2,3.0,1.3,1.8,NaN,0.7,9.0,2.940000
9,2008-01-01,10,3.2,2.7,4.3,2.3,3.4,2.2,2.8,1.2,2.2,1.7,3.5,3.3,1.3,5.3,NaN,1.2,10.0,3.293333
10,2008-01-01,11,2.3,2.8,4.1,2.8,3.4,2.4,2.2,1.3,1.9,4.4,2.7,2.3,1.4,3.9,NaN,1.3,11.0,3.260000
11,2008-01-01,12,2.2,3.1,5.3,3.8,3.5,2.8,2.3,1.4,2.1,4.4,3.7,NaN,3.6,5.0,NaN,1.4,12.0,3.942857
12,2008-01-01,13,2.4,2.7,5.8,4.2,4.1,3.2,2.3,1.5,2.2,5.9,4.1,NaN,6.8,5.0,NaN,1.5,13.0,4.514286
13,2008-01-01,14,4.5,4.9,6.4,6.1,6.0,4.0,3.9,2.2,3.8,6.0,5.3,NaN,6.9,5.5,NaN,2.2,14.0,5.678571
14,2008-01-01,15,3.8,4.2,5.8,4.7,4.6,4.5,4.7,2.3,4.3,5.1,5.6,3.4,6.6,5.5,NaN,2.3,15.0,5.340000
15,2008-01-01,16,4.1,5.2,7.0,5.7,4.7,3.9,4.1,2.4,3.8,6.0,5.9,2.9,8.2,6.2,NaN,2.4,16.0,5.740000
16,2008-01-01,17,4.4,4.3,6.6,4.4,5.5,4.1,5.3,2.9,4.7,5.3,6.8,3.7,6.2,6.4,NaN,2.9,17.0,5.840000
17,2008-01-01,18,3.9,4.1,6.2,5.1,5.2,4.4,4.4,2.8,4.1,5.6,6.3,3.7,6.5,4.8,NaN,2.8,18.0,5.673333
18,2008-01-01,19,3.6,4.3,6.2,4.9,4.7,3.9,4.3,2.6,3.7,6.2,5.4,2.9,5.9,4.0,NaN,2.6,19.0,5.440000
19,2008-01-01,20,3.7,4.4,6.1,5.1,4.6,4.0,3.5,2.0,4.0,5.6,6.1,3.0,6.7,4.5,NaN,2.0,20.0,5.553333
20,2008-01-01,21,3.4,4.2,5.3,5.3,4.1,3.9,2.4,2.3,2.9,6.0,5.7,2.7,6.7,5.5,NaN,2.3,21.0,5.426667
21,2008-01-01,22,3.4,3.9,5.2,4.7,4.0,3.4,2.8,1.8,3.1,5.5,4.5,3.3,6.0,6.6,NaN,1.8,22.0,5.346667
22,2008-01-01,23,3.6,3.9,4.5,4.4,3.7,2.9,2.6,1.4,2.8,5.2,4.3,3.5,6.2,6.6,NaN,1.4,23.0,5.240000
23,2008-01-01,24,4.1,3.3,4.6,3.9,3.6,3.0,2.7,1.4,3.0,4.8,4.3,3.4,5.8,7.2,NaN,1.4,24.0,5.273333
24,2008-01-02,1,3.9,3.6,5.0,4.5,4.0,2.9,2.4,1.5,2.9,4.5,4.9,3.1,5.4,5.8,NaN,1.0,5.8,3.693333
25,2008-01-02,2,3.7,3.4,6.2,3.4,4.3,2.9,3.0,1.5,3.4,3.0,4.2,3.5,5.8,5.5,NaN,1.5,6.2,3.720000
26,2008-01-02,3,2.7,NaN,5.9,2.9,4.3,3.3,2.7,1.6,2.9,3.4,3.9,2.8,5.4,5.4,NaN,1.6,5.9,3.585714
27,2008-01-02,4,2.8,NaN,5.5,2.7,4.2,3.3,2.6,1.4,2.9,2.6,3.4,3.0,4.3,5.0,NaN,1.4,5.5,3.407143
28,2008-01-02,5,2.6,NaN,4.9,2.5,4.0,2.8,2.2,NaN,2.7,2.6,3.0,2.6,4.4,5.2,NaN,2.2,5.2,3.423077
29,2008-01-02,6,2.5,NaN,5.2,2.9,3.9,2.7,2.5,NaN,3.0,2.3,2.9,2.1,4.4,5.1,NaN,2.1,6.0,3.500000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
8753,2008-12-30,18,2.2,NaN,3.2,1.6,2.8,2.3,2.0,2.4,2.0,1.8,NaN,NaN,NaN,3.6,3.2,1.6,18.0,3.758333
8754,2008-12-30,19,2.6,NaN,3.1,2.5,2.3,2.4,1.0,2.2,0.6,2.8,NaN,NaN,NaN,3.5,3.7,0.6,19.0,3.808333
8755,2008-12-30,20,1.1,NaN,2.4,1.5,1.8,1.8,1.4,2.0,0.5,1.9,NaN,NaN,NaN,2.3,2.4,0.5,20.0,3.258333
8756,2008-12-30,21,1.9,NaN,1.2,1.2,0.9,1.1,1.2,1.7,1.5,2.1,NaN,NaN,NaN,0.6,1.1,0.6,21.0,2.958333
8757,2008-12-30,22,1.2,NaN,1.6,2.2,1.0,0.6,1.2,1.7,1.0,1.4,NaN,NaN,NaN,0.2,0.7,0.2,22.0,2.900000
8758,2008-12-30,23,1.1,NaN,1.4,1.8,0.6,0.6,1.8,1.1,1.4,0.7,NaN,NaN,NaN,0.5,0.3,0.3,23.0,2.858333
8759,2008-12-30,24,1.0,NaN,0.7,1.3,0.7,0.4,1.5,1.2,1.4,1.2,NaN,NaN,NaN,1.3,1.4,0.4,24.0,3.008333
8760,2008-12-31,1,1.2,NaN,0.7,0.1,0.7,0.8,1.7,1.0,0.4,1.0,NaN,NaN,NaN,1.1,0.5,0.1,1.7,0.850000
8761,2008-12-31,2,1.2,NaN,1.0,1.5,0.6,1.5,1.0,0.3,0.5,0.6,NaN,NaN,NaN,0.5,0.7,0.3,2.0,0.950000
8762,2008-12-31,3,0.8,NaN,0.6,1.6,0.6,1.3,0.6,0.8,0.1,0.5,NaN,NaN,NaN,0.2,0.6,0.1,3.0,0.891667
8763,2008-12-31,4,0.8,NaN,1.1,0.3,NaN,0.4,1.0,0.6,0.6,1.0,NaN,NaN,NaN,0.6,0.7,0.3,4.0,1.009091
8764,2008-12-31,5,0.7,NaN,1.0,0.5,NaN,1.1,1.0,0.3,0.6,1.3,NaN,NaN,NaN,0.2,1.1,0.2,5.0,1.163636
8765,2008-12-31,6,0.5,NaN,0.8,0.4,NaN,0.4,1.5,0.5,0.5,0.6,NaN,NaN,NaN,1.3,0.6,0.4,6.0,1.190909
8766,2008-12-31,7,0.7,NaN,0.7,1.0,NaN,0.3,1.1,0.2,0.6,0.2,NaN,NaN,NaN,0.7,0.4,0.2,7.0,1.172727
8767,2008-12-31,8,0.9,NaN,1.1,1.0,0.3,0.2,1.7,0.7,0.8,0.6,NaN,NaN,NaN,0.3,0.6,0.2,8.0,1.350000
8768,2008-12-31,9,0.2,NaN,1.1,0.8,1.1,1.3,0.8,1.0,0.6,0.5,NaN,NaN,NaN,0.7,0.9,0.2,9.0,1.500000
8769,2008-12-31,10,0.6,NaN,0.9,1.4,1.2,1.0,1.0,0.8,1.0,0.6,NaN,NaN,NaN,1.0,0.9,0.6,10.0,1.700000
8770,2008-12-31,11,0.9,NaN,0.7,0.9,0.8,0.8,1.2,0.5,1.1,0.6,NaN,NaN,NaN,1.1,0.8,0.5,11.0,1.700000
8771,2008-12-31,12,1.2,NaN,1.0,0.3,1.4,0.6,1.1,0.8,1.1,0.5,NaN,NaN,NaN,1.0,1.2,0.3,12.0,1.850000
8772,2008-12-31,13,1.0,NaN,0.9,1.7,0.5,0.4,1.7,0.6,1.4,2.1,NaN,NaN,NaN,1.8,2.1,0.4,13.0,2.266667
8773,2008-12-31,14,2.0,NaN,2.6,2.0,0.5,0.9,1.1,1.8,2.0,2.1,NaN,NaN,NaN,1.4,2.2,0.5,14.0,2.716667
8774,2008-12-31,15,1.1,NaN,1.7,1.1,2.2,1.4,1.5,1.8,NaN,1.8,NaN,NaN,NaN,1.4,1.6,1.1,15.0,2.781818
8775,2008-12-31,16,1.4,NaN,2.1,2.2,2.2,0.8,1.9,NaN,NaN,2.1,NaN,NaN,NaN,2.2,1.4,0.8,16.0,3.230000
8776,2008-12-31,17,1.7,NaN,2.7,2.5,2.4,1.5,1.5,1.2,NaN,2.2,NaN,NaN,NaN,2.1,1.4,1.2,17.0,3.290909
8777,2008-12-31,18,2.5,NaN,3.2,2.6,2.7,1.5,2.1,1.6,2.0,3.3,NaN,NaN,NaN,2.4,1.9,1.5,18.0,3.650000
8778,2008-12-31,19,1.7,NaN,3.2,2.7,2.6,1.8,2.3,1.5,2.0,2.8,NaN,NaN,NaN,1.5,2.8,1.5,19.0,3.658333
8779,2008-12-31,20,2.3,NaN,3.9,3.1,2.7,2.3,1.4,2.7,1.8,3.2,NaN,NaN,NaN,1.2,3.8,1.2,20.0,4.033333
8780,2008-12-31,21,2.4,NaN,3.6,2.5,2.2,2.3,2.1,2.1,2.1,1.7,NaN,NaN,NaN,3.2,3.8,1.7,21.0,4.083333
8781,2008-12-31,22,2.2,NaN,3.5,2.7,1.6,1.8,2.3,1.6,2.1,1.7,NaN,NaN,NaN,5.1,3.2,1.6,22.0,4.150000
8782,2008-12-31,23,2.3,NaN,3.6,2.5,1.8,1.9,1.6,0.7,1.5,2.3,NaN,NaN,NaN,3.2,3.1,0.7,23.0,3.958333

In [ ]:
Prom=df.mean(axis=1)

In [ ]:
Min=df.min(axis=1)

In [ ]:
df.head()

In [ ]:
df['Max'].describe()

In [ ]:
Pro_03 = df[['FECHA','Prom','Min','Max']].copy()

In [ ]:
Pro_03.head()

In [ ]:
Pro_03.describe()

In [ ]:
Pro_03.to_excel('Datos_2008WSP.xlsx')

In [ ]:
gr = df.groupby('FECHA')

In [ ]:
df.describe()